[tool.black]
line-length = 120
target-version = ['py37']
extend-exclude = '''
^/\.git
^/\.vscode
^/\.github
'''

[tool.isort]
line_length=120
profile="black"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-s -ra -q --cov=aiophotoprism --cov-report=html"
testpaths = [
    "tests"
]